### PR TITLE
Add Realme XT (RMX1921) to official devices

### PR DESCRIPTION
**Pull request by improbir**

### CODE REVIEW

**Comment by improbir** [comment]
add realme title too otherwise everyone will get build error

**Comment by SKULSHADY** [comment]
Please fix it

**Comment by improbir** [comment]
i  am afraid of these two lines "android:id="@+id/device_category_realme"-"android:title="@string/device_category_realme_title". Cause previously when i tried to build i got error like " Realme title is missing". Immediately i searched for java code but not found any for title related. I have pushed all xml related code... you need to investigate this sir.

**Comment by improbir** [comment]
> Please fix it

I am afraid of these two lines "android:id="@+id/device_category_realme"-"android:title="@string/device_category_realme_title". Cause previously when i tried to build i got error like " Realme title is missing". Immediately i searched for java code but not found any for title related. I have pushed all xml related code... you need to investigate this sir.

**Comment by improbir** [comment]
> Please fix

**Pull request closed without merging**
